/local_costmap/footprint, geometry_msgs/msg/Polygon
/global_costmap/footprint, geometry_msgs/msg/Polygon

Point32[] points
	#
	#
	float32 x
	float32 y
	float32 z

points:
  - [1000 instances of {x: 1.0, y: 1.0, z: 1.0}]

points:
  - x: 3.4028235e+38
    y: -3.4028235e+38
    z: 3.4028235e+38
  - x: -3.4028235e+38
    y: 3.4028235e+38
    z: -3.4028235e+38

points:
  - [100 instances alternating between {x: 1e+10, y: 0.0, z: 0.0} and {x: -1e+10, y: 0.0, z: 0.0}]

points:
  - x: 1.0
    y: 1.0
    z: 1.0
  - x: 2.0
    y: 2.0
    z: 2.0
  - x: 3.0
    y: 3.0
    z: 3.0
  - x: 4.0
    y: 4.0
    z: 4.0

